# Generated by Django 5.1.2 on 2024-10-29 16:15

import FurryFunnies.author.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[FurryFunnies.author.utils.ValidatorOnlyLetters(), django.core.validators.MinLengthValidator(4)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), FurryFunnies.author.utils.ValidatorOnlyLetters])),
                ('passcode', models.CharField(help_text='Your passcode must be a combination of 6 digits.', max_length=6, validators=[FurryFunnies.author.utils.ValidatorPasscode()])),
                ('pets_number', models.PositiveSmallIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Oops! That title is already taken. How about something fresh and fun?'}, max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('image_url', models.URLField(help_text='Share your funniest furry photo URL!')),
                ('content', models.TextField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='author.author')),
            ],
        ),
    ]
